### ISSUE TITLE
Stash tab overlay doesnt update as I grab items, and cannot "edit" overlay location.

### ISSUE THREAD

**Issue by Deke0n** [ChaosRecipeEnhancer/ChaosRecipeEnhancer#263]
Edit button does not work on overlay, highlight doesn't update as I grab item by item or set by set.

**Comment by HiMarioLopez** [comment]
Hi, we just updated the app to version v1.3.0 with #268 

After installation could you tell me if your issue is still present?

Thanks!

**Comment by cincydan** [comment]
I am running 1.3.1 and having this same issue.  The edit button is not active (I click and nothing happens) for the grid.  I am using a large tv for my monitor and the bottom of the grid is cut off, so I am not sure if this is the issue.

**Comment by HiMarioLopez** [comment]
Any updates or am I clear to close this? We just released v1.4.0 with more bug fixes, and will have another patch out early next week.

**Comment by Saveyy** [comment]
i just downloaded newest version and still have this problem

**Comment by HiMarioLopez** [comment]
Any screenshots of your settings and of the problem are much appreciated!

**Comment by Saveyy** [comment]
i restartet chaosrecipe-application and launched it in administrator mode. Works like a charm now

**Comment by HiMarioLopez** [comment]
Awesome! Will add this to the trouble-shooting tips if others have similar issues. Thanks!

**Comment by Saveyy** [comment]
@HiMarioLopez just a headsup- i'm not Original poster of htis problem., - might not be fixed for OP

**Comment by HiMarioLopez** [comment]
Yes, correct. Given the issue is from November of last year, I'm gonna ask @Deke0n to open a new issue if the update / admin fix doesn't work. Want to clear out some of these older issues and will soon have a proper issue template to give me more info right off the bat
